language: python

python:
  - 2.7
  - 3.3
  - 3.4

install:
  - npm install -g grunt-cli
  - npm install
  - npm run-script devsetup

script:
  - grunt
  - cd test/integration_test
  - ./run_test.sh

notifications:
  email: false
